name: akdr_weather
description: "Weather Application "
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  hive: ^2.2.3
  http: ^1.2.1
  sqflite: ^2.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF
      fonts:
        - asset: assets/fonts/SF_PRO.ttf
  assets:
    - assets/Images/

